functionsDirectory = "/Users/stephansmith/Documents/Koo/v2/netlify/functions"
functionsDirectoryOrigin = "ui"
redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/stephansmith/Documents/Koo/v2/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "/Users/stephansmith/Documents/Koo/v2/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]